CREATE DATABASE IF NOT EXISTS speednet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE speednet;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(30) UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS otp_codes (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(30), otp_code VARCHAR(6), expires_at DATETIME, verified TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_phone (phone));
CREATE TABLE IF NOT EXISTS payments (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(30), bundle_name VARCHAR(255), amount DECIMAL(10,2), method VARCHAR(30), reference_id VARCHAR(255), status VARCHAR(40), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS esims (id INT AUTO_INCREMENT PRIMARY KEY, phone VARCHAR(30), bundle_name VARCHAR(255), qr_data TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
